export const REQUEST_USER_PENDING='REQUEST_USER_PENDING'
export const REQUEST_USER_SUCCESS='REQUEST_USER_SUCCESS'
export const REQUEST_USER_FAILED='REQUEST_USER_FAILED'
export const REQUEST_SIGNOUT='REQUEST_SIGNOUT'

export const REQUEST_POSTS_PENDING='REQUEST_POSTS_PENDING'
export const REQUEST_POSTS_SUCCESS='REQUEST_POSTS_SUCCESS'
export const REQUEST_POSTS_FAILED='REQUEST_POSTS_FAILED'


export const REQUEST_POST_PENDING='REQUEST_POST_PENDING'
export const REQUEST_POST_SUCCESS='REQUEST_POST_SUCCESS'
export const REQUEST_POST_FAILED='REQUEST_POST_FAILED'

export const UPDATE_POST_PENDING='UPDATE_POST_PENDING'
export const UPDATE_POST_SUCCESS='UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAILED='UPDATE_POST_FAILED'


export const DELETE_POST_PENDING='DELETE_POST_PENDING'
export const DELETE_POST_SUCCESS='DELETE_POST_SUCCESS'
export const DELETE_POST_FAILED='DELETE_POST_FAILED'


export const CREATE_POST_PENDING='CREATE_POST_PENDING'
export const CREATE_POST_SUCCESS='CREATE_POST_SUCCESS'
export const CREATE_POST_FAILED='CREATE_POST_FAILED'

export const SIGNUP_PENDING='SIGNUP_PENDING'
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS'
export const SIGNUP_FAILED='SIGNUP_FAILED'
